[gemini]
gemini_key = "AIzaSyBnI8QXT7tDSO7Do0j0URBfEw9xP1gNTxQ"
api_key = "AIzaSyBnI8QXT7tDSO7Do0j0URBfEw9xP1gNTxQ"

[deepseek]
deepseek_key = "sk-e7a6ddf644fe48f99ab19c541e926daby"
api_base = "https://api.deepseek.com/v1"